export const FAITH_WISDOM_CARDS = [
  { id: 1, title: "Absolute Honesty", verse: "Proverbs 11:1", quote: "The Lord detests dishonest scales, but accurate weights find favor.", application: "Never misrepresent market values or repair estimates. Transparent numbers build trust." },
  { id: 2, title: "Just Balances", verse: "Proverbs 16:11", quote: "A just balance and scales are the Lord’s; all the weights in the bag are his work.", application: "Ensure every wholesale fee and seller payout is fair and completely ethical." },
  { id: 3, title: "Diligent Hands", verse: "Proverbs 12:24", quote: "Diligent hands will rule, but laziness ends in forced labor.", application: "Execute your real estate follow-ups and CRM tasks with excellence and discipline." },
  { id: 4, title: "Excellence in Work", verse: "Proverbs 22:29", quote: "Do you see someone skilled in their work? They will serve before kings...", application: "Master your scripts, underwriting, and contracts. True professionals stand out instantly to sellers." },
  { id: 5, title: "Listen Before Speaking", verse: "Proverbs 18:13", quote: "To answer before listening— that is folly and shame.", application: "Don't prematurely pitch an offer. Hear the seller's full situation before presenting a solution." },
  { id: 6, title: "Quick to Listen", verse: "James 1:19", quote: "Everyone should be quick to listen, slow to speak and slow to become angry.", application: "Let the seller talk through their pain. Validate their feelings before giving numbers." },
  { id: 7, title: "Grace & Salt", verse: "Colossians 4:6", quote: "Let your speech always be gracious, seasoned with salt...", application: "Operate with absolute integrity. Provide a bridge of peace, even when a seller is hostile." },
  { id: 8, title: "The Generous Soul", verse: "Proverbs 11:25", quote: "A generous person will prosper; whoever refreshes others will be refreshed.", application: "Approach every seller with a heart to genuinely help them solve their specific real estate crisis." },
  { id: 9, title: "Servant Posture", verse: "Matthew 20:26", quote: "Whoever wants to become great among you must be your servant.", application: "Focus entirely on solving the seller's specific burden, even if it directs them to another buyer." },
  { id: 10, title: "Do Not Grow Weary", verse: "Galatians 6:9", quote: "Let us not become weary in doing good, for at the proper time we will reap a harvest if we do not give up.", application: "Stay consistent in your 6-month drip campaigns and continuous seller follow-ups." },
  { id: 11, title: "Perfect Peace", verse: "Isaiah 26:3", quote: "You will keep in perfect peace those whose minds are steadfast, because they trust in you.", application: "Remain utterly unbothered when a deal falls through; trust that God has a better one waiting." },
  { id: 12, title: "Peace in Trials", verse: "Philippians 4:6", quote: "Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God.", application: "Maintain a calm, grounded spirit during hostile negotiations, title issues, or difficult pushbacks." },
  { id: 13, title: "Power and Sound Mind", verse: "2 Timothy 1:7", quote: "For the Spirit God gave us does not make us timid, but gives us power, love and self-discipline.", application: "Make confident cold calls and negotiate firmly. Fear has no place in your business." },
  { id: 14, title: "Honoring Your Word", verse: "Psalm 15:4", quote: "Who keeps an oath even when it hurts, and does not change their mind...", application: "If you committed to an earnest money deposit or closing date, follow through even if your buyer backs out." },
  { id: 15, title: "Fulfilling Vows", verse: "Ecclesiastes 5:4", quote: "When you make a vow to God, do not delay to fulfill it...", application: "Your signature on a purchase agreement is a promise. Execute your contracts with conviction." },
  { id: 16, title: "Divine Discernment", verse: "James 1:5", quote: "If any of you lacks wisdom, you should ask God, who gives generously to all...", application: "Ask God for insight on live calls to uncover the true root motivation driving the distressed seller." },
  { id: 17, title: "Let Your Yes Be Yes", verse: "Matthew 5:37", quote: "All you need to say is simply ‘Yes’ or ‘No’...", application: "Don't drag out a dead deal. Give a fast, clear 'No' if the numbers don't work for you." },
  { id: 18, title: "Faithful in Little", verse: "Luke 16:10", quote: "Whoever can be trusted with very little can also be trusted with much...", application: "Treat the $3,000 wholesale deal with the same respect and attention as the $50,000 flip." },
  { id: 19, title: "Gentle Answers", verse: "Proverbs 15:1", quote: "A gentle answer turns away wrath, but a harsh word stirs up anger.", application: "Defuse angry sellers by lowering your tone and responding with profound empathy." },
  { id: 20, title: "Commit Your Plans", verse: "Proverbs 16:3", quote: "Commit to the Lord whatever you do, and he will establish your plans.", application: "Surrender your KPIs, call volumes, and revenue goals to Him daily before hitting the dialer." },
  { id: 21, title: "Live at Peace", verse: "Romans 12:18", quote: "If it is possible, as far as it depends on you, live at peace with everyone.", application: "When a seller or partner dispute arises, strive for fair resolution rather than escalating into legal battles." },
  { id: 22, title: "Build Others Up", verse: "Ephesians 4:29", quote: "Do not let any unwholesome talk come out of your mouths, but only what is helpful for building others up...", application: "Speak life and encouragement into the distressed situations of those facing foreclosure or loss." },
  { id: 23, title: "Diligent Planning", verse: "Proverbs 21:5", quote: "The plans of the diligent lead to profit as surely as haste leads to poverty.", application: "Never blindly guess ARV or rehab costs. Thoroughly underwrite every deal before pitching a price." },
  { id: 24, title: "Trust His Direction", verse: "Proverbs 3:5-6", quote: "Trust in the Lord with all your heart and lean not on your own understanding...", application: "When the real estate market shifts, lean on His provision rather than panicking over interest rates." },
  { id: 25, title: "Walking in Truth", verse: "3 John 1:4", quote: "I have no greater joy than to hear that my children are walking in the truth.", application: "Keep your word on every assignment fee, joint venture split, and closing contingency." },
  { id: 26, title: "Strength in Quietness", verse: "Isaiah 30:15", quote: "In repentance and rest is your salvation, in quietness and trust is your strength...", application: "Do not rush or panic during dead air on a phone call. Let the seller fill the silence." },
  { id: 27, title: "The Golden Rule", verse: "Matthew 7:12", quote: "So in everything, do to others what you would have them do to you...", application: "If it was your own mother selling this house, how would you want an investor to treat her?" },
  { id: 28, title: "Walk in Wisdom", verse: "Colossians 4:5", quote: "Be wise in the way you act toward outsiders; make the most of every opportunity.", application: "Treat every lead as a divine appointment. Be tactful, professional, and maximize every conversation." },
  { id: 29, title: "Overcoming Evil with Good", verse: "Romans 12:21", quote: "Do not be overcome by evil, but overcome evil with good.", application: "If a competitor steals a deal or bad-mouths you, respond with grace and continue serving your market." },
  { id: 30, title: "Serving the Least of These", verse: "Matthew 25:40", quote: "Whatever you did for one of the least of these brothers and sisters of mine, you did for me.", application: "Treat hoarder houses and highly distressed individuals with the utmost dignity and respect." },
  { id: 31, title: "Work as to the Lord", verse: "Colossians 3:23", quote: "Whatever you do, work at it with all your heart, as working for the Lord, not for human masters.", application: "Make your cold calls and manage your CRM as if Jesus Himself was your Sales Manager." },
  { id: 32, title: "Seeking Wise Counsel", verse: "Proverbs 11:14", quote: "For lack of guidance a nation falls, but victory is won through many advisers.", application: "Don't isolate yourself in this business. Seek mentorship and consult experienced investors on complex deals." },
  { id: 33, title: "The Value of a Good Name", verse: "Proverbs 22:1", quote: "A good name is more desirable than great riches; to be esteemed is better than silver or gold.", application: "Never compromise your reputation for a quick wholesale fee. Your integrity is your best marketing." },
  { id: 34, title: "Guarding Your Heart", verse: "Proverbs 4:23", quote: "Above all else, guard your heart, for everything you do flows from it.", application: "Protect your mindset. Don't let the rejection of 100 'no's poison your attitude toward the next lead." },
  { id: 35, title: "Patience in the Process", verse: "Romans 5:3-4", quote: "We also glory in our sufferings, because we know that suffering produces perseverance...", application: "Endure the friction of lead generation. Perseverance builds the character needed to sustain wealth." },
  { id: 36, title: "Rejoice in Hope", verse: "Romans 12:12", quote: "Be joyful in hope, patient in affliction, faithful in prayer.", application: "When the market is tough, remain hopeful, grind through the affliction, and pray over your pipeline." },
  { id: 37, title: "Humility Before Honor", verse: "Proverbs 15:33", quote: "Wisdom’s instruction is to fear the Lord, and humility comes before honor.", application: "Don't act like the smartest person in the room. Be humble enough to learn from every seller you meet." },
  { id: 38, title: "The Snare of Hasty Words", verse: "Proverbs 29:20", quote: "Do you see someone who speaks in haste? There is more hope for a fool than for them.", application: "Pause before reacting to a low-ball counteroffer. Think strategically, not emotionally." },
  { id: 39, title: "Avoiding Greed", verse: "Luke 12:15", quote: "Watch out! Be on your guard against all kinds of greed; life does not consist in an abundance of possessions.", application: "Don't squeeze every last penny out of a seller if it hurts them. Leave meat on the bone for others." },
  { id: 40, title: "Sowing and Reaping", verse: "2 Corinthians 9:6", quote: "Whoever sows sparingly will also reap sparingly, and whoever sows generously will also reap generously.", application: "Your outbound marketing and follow-ups are seeds. Plant abundantly to harvest a consistent pipeline." },
  { id: 41, title: "The Blessing of Hard Work", verse: "Proverbs 14:23", quote: "All hard work brings a profit, but mere talk leads only to poverty.", application: "Stop watching podcasts and start dialing. Action produces contracts, theory produces nothing." },
  { id: 42, title: "Walking in Integrity", verse: "Proverbs 10:9", quote: "Whoever walks in integrity walks securely, but whoever takes crooked paths will be found out.", application: "Never forge signatures, hide material defects, or manipulate closing documents. The truth always comes to light." },
  { id: 43, title: "Trusting God’s Timing", verse: "Ecclesiastes 3:1", quote: "There is a time for everything, and a season for every activity under the heavens...", application: "Recognize that not every seller is ready to sell today. Nurture them until their season arrives." },
  { id: 44, title: "Speak Truth to Your Neighbor", verse: "Zechariah 8:16", quote: "These are the things you are to do: Speak the truth to each other, and render true and sound judgment...", application: "Be incredibly upfront about the condition of a property when marketing it to cash buyers." },
  { id: 45, title: "Deliver Those Drawn Toward Death", verse: "Proverbs 24:11", quote: "Rescue those being led away to death; hold back those staggering toward slaughter.", application: "Step in boldly to help sellers facing imminent foreclosure. You are their life raft." },
  { id: 46, title: "Bearing One Another’s Burdens", verse: "Galatians 6:2", quote: "Carry each other’s burdens, and in this way you will fulfill the law of Christ.", application: "Wholesaling is burden-bearing. Take on the stress of the trashed property so the seller doesn't have to." },
  { id: 47, title: "Flee from Love of Money", verse: "1 Timothy 6:10", quote: "For the love of money is a root of all kinds of evil...", application: "Make money to fund the Kingdom and your family, but never let the pursuit of a deal compromise your soul." },
  { id: 48, title: "The Lord Weighs the Heart", verse: "Proverbs 21:2", quote: "A person may think their own ways are right, but the Lord weighs the heart.", application: "Check your motives before closing a deal. Are you truly helping them, or just taking advantage?" },
  { id: 49, title: "Providing for Your Family", verse: "1 Timothy 5:8", quote: "Anyone who does not provide for their relatives, and especially for their own household, has denied the faith...", application: "Your hustle on the phones is a holy endeavor to protect and provide for your household." },
  { id: 50, title: "Avoiding Debt", verse: "Proverbs 22:7", quote: "The rich rule over the poor, and the borrower is slave to the lender.", application: "Structure creative finance deals responsibly, and avoid over-leveraging yourself into a corner." },
  { id: 51, title: "Righteous Boldness", verse: "Proverbs 28:1", quote: "The wicked flee though no one pursues, but the righteous are as bold as a lion.", application: "You have the right solution. Speak with absolute conviction when presenting your cash offer." },
  { id: 52, title: "Do Not Despise Small Beginnings", verse: "Zechariah 4:10", quote: "Who dares despise the day of small things, since the seven eyes of the Lord that range throughout the earth will rejoice...", application: "Celebrate the small victories: a good conversation, a returned call, or your first $1k assignment fee." },
  { id: 53, title: "Wisdom is Better than Rubies", verse: "Proverbs 8:11", quote: "For wisdom is more precious than rubies, and nothing you desire can compare with her.", application: "Invest continually in your real estate education and spiritual growth before seeking mere payouts." },
  { id: 54, title: "The Prudent See Danger", verse: "Proverbs 22:3", quote: "The prudent see danger and take refuge, but the simple keep going and pay the penalty.", application: "Always run a title search early and verify taxes/liens before promising a seller a smooth closing." },
  { id: 55, title: "A Cheerful Heart", verse: "Proverbs 17:22", quote: "A cheerful heart is good medicine, but a crushed spirit dries up the bones.", application: "Bring positive, uplifting energy to every appointment. Sellers are drawn to joy in the midst of their crisis." },
  { id: 56, title: "Let Love Be Genuine", verse: "Romans 12:9", quote: "Love must be sincere. Hate what is evil; cling to what is good.", application: "Don't fake empathy to get a contract. Truly care about their situation, and the contract will follow." },
  { id: 57, title: "Do Not Be Anxious About Tomorrow", verse: "Matthew 6:34", quote: "Therefore do not worry about tomorrow, for tomorrow will worry about itself. Each day has enough trouble of its own.", application: "Focus entirely on the calls and follow-ups you need to make today. Don't stress over next month's pipeline." },
  { id: 58, title: "The Plans of the Heart", verse: "Proverbs 16:9", quote: "In their hearts humans plan their course, but the Lord establishes their steps.", application: "You can map out a complex sub-to strategy, but remain adaptable if God pivots the deal entirely." },
  { id: 59, title: "Seek First the Kingdom", verse: "Matthew 6:33", quote: "But seek first his kingdom and his righteousness, and all these things will be given to you as well.", application: "Prioritize your spiritual health and integrity above your business metrics. The success will follow." },
  { id: 60, title: "Endurance Produces Character", verse: "Romans 5:4", quote: "Endurance produces character, and character produces hope...", application: "Those months with zero closed deals are actively forging the resilience you need for long-term success." },
  { id: 61, title: "Giving Cheerfully", verse: "2 Corinthians 9:7", quote: "Each of you should give what you have decided in your heart to give, not reluctantly or under compulsion...", application: "Be generous with your time, your advice to sellers, and your tithes from your assignment fees." },
  { id: 62, title: "Do All to the Glory of God", verse: "1 Corinthians 10:31", quote: "So whether you eat or drink or whatever you do, do it all for the glory of God.", application: "Let every cold call, every property walk-through, and every closing be an act of worship in excellence." },
  { id: 63, title: "Iron Sharpens Iron", verse: "Proverbs 27:17", quote: "As iron sharpens iron, so one person sharpens another.", application: "Surround yourself with other faith-driven investors who hold you accountable to high ethical standards." },
  { id: 64, title: "The Laborer is Worthy", verse: "1 Timothy 5:18", quote: "For Scripture says, 'Do not muzzle an ox while it is treading out the grain,' and 'The worker deserves his wages.'", application: "Do not feel guilty for making a healthy profit. You solved a massive problem and earned your assignment fee." },
  { id: 65, title: "Do Not Lie to Each Other", verse: "Colossians 3:9", quote: "Do not lie to each other, since you have taken off your old self with its practices...", application: "Never tell a seller you are buying the property 'cash' if you don't actually have the cash or a solid buyer network." },
  { id: 66, title: "Patience with Everyone", verse: "1 Thessalonians 5:14", quote: "And we urge you, brothers and sisters, warn those who are idle and disruptive, encourage the disheartened, help the weak, be patient with everyone.", application: "Be incredibly patient with elderly sellers or those who don't understand the real estate process." },
  { id: 67, title: "Taming the Tongue", verse: "James 3:5", quote: "Likewise, the tongue is a small part of the body, but it makes great boasts. Consider what a great forest is set on fire by a small spark.", application: "Watch what you say in negotiations. A single arrogant or impatient comment can burn down a lucrative deal." },
  { id: 68, title: "A Time to Keep Silence", verse: "Ecclesiastes 3:7", quote: "...a time to tear and a time to mend, a time to be silent and a time to speak...", application: "Once you drop your offer price, shut up. The next person to speak loses leverage." },
  { id: 69, title: "Dealing Fairly", verse: "Leviticus 19:35", quote: "Do not use dishonest standards when measuring length, weight or quantity.", application: "Use accurate ARV comps. Don't intentionally pull low comps to artificially deflate the seller's expectations." },
  { id: 70, title: "Bless Those Who Curse You", verse: "Luke 6:28", quote: "Bless those who curse you, pray for those who mistreat you.", application: "When a seller yells at you on a cold call, don't yell back. Bless them, log it in the CRM, and move on." },
  { id: 71, title: "Anxiety Weighs Down", verse: "Proverbs 12:25", quote: "Anxiety weighs down the heart, but a kind word cheers it up.", application: "Sellers are often drowning in anxiety over debt. Be the kind, reassuring voice that brings them relief." },
  { id: 72, title: "Do Not Withhold Good", verse: "Proverbs 3:27", quote: "Do not withhold good from those to whom it is due, when it is in your power to act.", application: "If you know a great retail agent that would serve the seller better than your cash offer, refer them out." },
  { id: 73, title: "Let Your Light Shine", verse: "Matthew 5:16", quote: "In the same way, let your light shine before others, that they may see your good deeds and glorify your Father in heaven.", application: "Run your wholesaling business so ethically that title companies and closing attorneys notice the difference." },
  { id: 74, title: "The Lord Provides", verse: "Genesis 22:14", quote: "So Abraham called that place The Lord Will Provide. And to this day it is said, 'On the mountain of the Lord it will be provided.'", application: "If a massive deal falls through at the 11th hour, rest in Jehovah Jireh. He will provide the next one." },
  { id: 75, title: "Walk Circumspectly", verse: "Ephesians 5:15-16", quote: "Be very careful, then, how you live—not as unwise but as wise, making the most of every opportunity, because the days are evil.", application: "Be highly efficient with your dialer time and marketing dollars. Steward your daily schedule wisely." },
  { id: 76, title: "Settle Matters Quickly", verse: "Matthew 5:25", quote: "Settle matters quickly with your adversary who is taking you to court...", application: "If there's an earnest money dispute or a clouded title issue, aim for a quick, amicable settlement over litigation." },
  { id: 77, title: "Be Strong and Courageous", verse: "Joshua 1:9", quote: "Have I not commanded you? Be strong and courageous. Do not be afraid; do not be discouraged, for the Lord your God will be with you wherever you go.", application: "Don't be intimidated by big numbers, complex commercial deals, or aggressive closing attorneys. Stand firm." },
  { id: 78, title: "The Fear of Man", verse: "Proverbs 29:25", quote: "Fear of man will prove to be a snare, but whoever trusts in the Lord is kept safe.", application: "Don't be afraid of offending a seller by presenting a low cash offer. If it's a fair underwriting, present it confidently." },
  { id: 79, title: "Do Everything in Love", verse: "1 Corinthians 16:14", quote: "Do everything in love.", application: "Even when sending out thousands of cold texts or running cold calling campaigns, let your underlying motive be love." },
  { id: 80, title: "Consider the Ant", verse: "Proverbs 6:6-8", quote: "Go to the ant, you sluggard; consider its ways and be wise! It has no commander... yet it stores its provisions in summer and gathers its food at harvest.", application: "Build systems, automations, and a robust pipeline so you aren't scrambling for a deal in the winter months." },
  { id: 81, title: "Riches Fade", verse: "Proverbs 23:4-5", quote: "Do not wear yourself out to get rich; do not trust your own cleverness. Cast but a glance at riches, and they are gone...", application: "Don't burn out your family life trying to close one more deal. Keep wealth in its proper, secondary place." },
  { id: 82, title: "Weep with Those Who Weep", verse: "Romans 12:15", quote: "Rejoice with those who rejoice; mourn with those who mourn.", application: "When dealing with probate or inherited properties, pause your pitch to genuinely mourn their loss with them." },
  { id: 83, title: "Wisdom from Above", verse: "James 3:17", quote: "But the wisdom that comes from heaven is first of all pure; then peace-loving, considerate, submissive, full of mercy and good fruit, impartial and sincere.", application: "Ensure your contracts and negotiations are pure, sincere, and never rely on shady loopholes." },
  { id: 84, title: "Pay What You Owe", verse: "Romans 13:7", quote: "Give to everyone what you owe them: If you owe taxes, pay taxes; if revenue, then revenue; if respect, then respect; if honor, then honor.", application: "Pay your bird dogs, cold callers, and joint venture partners exactly what you promised, right on time." },
  { id: 85, title: "Delight in the Lord", verse: "Psalm 37:4", quote: "Take delight in the Lord, and he will give you the desires of your heart.", application: "Find your ultimate joy in Christ, not in your closed volume. He will align your real estate goals with His will." },
  { id: 86, title: "Commit Your Way", verse: "Psalm 37:5", quote: "Commit your way to the Lord; trust in him and he will do this:", application: "When a deal seems hopelessly stuck in probate, commit the process to the Lord and trust His outcome." },
  { id: 87, title: "The Generous Eye", verse: "Proverbs 22:9", quote: "The generous will themselves be blessed, for they share their food with the poor.", application: "Consider donating a portion of your assignment fees to local ministries or helping a seller with moving costs." },
  { id: 88, title: "No Condemnation", verse: "Romans 8:1", quote: "Therefore, there is now no condemnation for those who are in Christ Jesus,", application: "When you make a massive mistake on a rehab estimate and lose money, learn from it but don't condemn yourself." },
  { id: 89, title: "A Soft Answer", verse: "Proverbs 25:15", quote: "Through patience a ruler can be persuaded, and a gentle tongue can break a bone.", application: "You can negotiate massive price reductions simply by remaining patient, soft-spoken, and remarkably persistent." },
  { id: 90, title: "Walk in the Light", verse: "1 John 1:7", quote: "But if we walk in the light, as he is in the light, we have fellowship with one another, and the blood of Jesus, his Son, purifies us from all sin.", application: "Keep your business dealings entirely in the light. No hidden fees, no secret agendas." },
  { id: 91, title: "Count the Cost", verse: "Luke 14:28", quote: "Suppose one of you wants to build a tower. Won’t you first sit down and estimate the cost to see if you have enough money to complete it?", application: "Never start a fix-and-flip without a fully dialed-in scope of work, budget, and contingency fund." },
  { id: 92, title: "Be Doers of the Word", verse: "James 1:22", quote: "Do not merely listen to the word, and so deceive yourselves. Do what it says.", application: "Don't just listen to wholesaling podcasts. Pick up the phone, knock on doors, and do the actual work." },
  { id: 93, title: "God Provides the Increase", verse: "1 Corinthians 3:7", quote: "So neither the one who plants nor the one who waters is anything, but only God, who makes things grow.", application: "You can pull the lists and send the mailers, but ultimately, God is the one who brings the contract." },
  { id: 94, title: "Stewardship", verse: "1 Peter 4:10", quote: "Each of you should use whatever gift you have received to serve others, as faithful stewards of God’s grace in its various forms.", application: "Use your gift of negotiation and market knowledge to protect sellers from predatory buyers." },
  { id: 95, title: "The Profit of the Earth", verse: "Ecclesiastes 5:9", quote: "The increase from the land is taken by all; the king himself profits from the fields.", application: "Real estate is a God-ordained vehicle for wealth generation. Steward the properties you buy with excellence." },
  { id: 96, title: "Stand Firm", verse: "1 Corinthians 15:58", quote: "Therefore, my dear brothers and sisters, stand firm. Let nothing move you. Always give yourselves fully to the work of the Lord...", application: "Stand firm when buyers try to re-trade you at the closing table. Hold your ground and enforce your contracts." },
  { id: 97, title: "Let Patience Have Its Perfect Work", verse: "James 1:4", quote: "Let perseverance finish its work so that you may be mature and complete, not lacking anything.", application: "Real estate is a long game. Let the slow seasons build your maturity rather than causing you to quit." },
  { id: 98, title: "Do Not Boast About Tomorrow", verse: "Proverbs 27:1", quote: "Do not boast about tomorrow, for you do not know what a day may bring.", application: "Never spend an assignment fee before it actually crosses the closing table and hits your bank account." },
  { id: 99, title: "God Hates False Balances", verse: "Proverbs 20:23", quote: "The Lord detests differing weights, and dishonest scales do not please him.", application: "Don't have one set of rules for how you treat buyers and a different, unfair set for how you treat sellers." },
  { id: 100, title: "Rest in Him", verse: "Matthew 11:28", quote: "Come to me, all you who are weary and burdened, and I will give you rest.", application: "When the hustle of real estate leaves you burned out, unplug, observe the Sabbath, and find your rest in Him." }
];

export function getRandomWisdomCard(excludeId = null) {
  let available = FAITH_WISDOM_CARDS;
  if (excludeId) {
    available = FAITH_WISDOM_CARDS.filter(c => c.id !== excludeId);
  }
  const randomIndex = Math.floor(Math.random() * available.length);
  return available[randomIndex];
}

export function getRandomWisdomCards(count = 3, currentIds = []) {
  let available = FAITH_WISDOM_CARDS.filter(c => !currentIds.includes(c.id));
  const selected = [];
  for (let i = 0; i < count; i++) {
    if (available.length === 0) break;
    const randomIndex = Math.floor(Math.random() * available.length);
    selected.push(available[randomIndex]);
    available.splice(randomIndex, 1);
  }
  return selected;
}
