const fs = require('fs'); 
let c = fs.readFileSync('src/components/documents/TearSheet.jsx', 'utf-8'); 
c = c.replace(/className=\"text-\[\#d97706\]\"/g, 'className="text-[#00E5FF]"');
c = c.replace(/className=\"bg-white rounded-xl border-2 border-black shadow-\[0_10px_20px_rgba\(0,0,0,0.8\)\] overflow-hidden\"/g, 'className="bg-white border-4 border-black shadow-[6px_6px_0px_#000] overflow-hidden"');
c = c.replace(/<img src=\"\/assets\/steampunk\/wax_seal.png\" alt=\"Wax Seal\" className=\"w-full h-full object-contain drop-shadow-2xl\" \/>/g, '<div className="w-full h-full flex items-center justify-center font-bangers text-6xl text-[#FF0055] drop-shadow-md transform -skew-x-6" style={{textShadow: "4px 4px 0px #000"}}>THWIP!</div>');
c = c.replace(/text-\[\#451a03\]/g, 'text-black');
c = c.replace(/text-\[\#78350f\]/g, 'text-black');
c = c.replace(/text-\[\#166534\]/g, 'text-[#00E676]');
c = c.replace(/Ready to push to disposition\? Impress the wax seal to generate the tear-sheet draft./g, 'Ready to push to disposition? Smash the button to generate the tear-sheet draft.');
c = c.replace(/isGenerating \? \"bg-\[\#78350f\] text-black opacity-90\" : \"bg-\[\#78350f\] hover:bg-\[\#b45309\] text-black hover:shadow-\[inset_0_2px_10px_rgba\\(255,255,255,0.4\\),0_0_15px_\#d97706\]\"/g, 'isGenerating ? "bg-[#00E5FF] text-black neon-glow-cyan" : "bg-[#FF0055] hover:bg-[#00E5FF] hover:text-black text-white hover:shadow-[6px_6px_0px_#000]"');
c = c.replace(/isGenerating \? \"PRESSING SEAL\.\.\.\" : \"IMPRESS SEAL\"/g, 'isGenerating ? "GENERATING..." : "GENERATE TEAR-SHEET"');
c = c.replace(/bg-white p-6 rounded-xl border-2 border-black relative shadow-\[0_10px_20px_rgba\(0,0,0,0.8\)\]/g, 'bg-white p-6 border-4 border-black relative shadow-[6px_6px_0px_#000]');
c = c.replace(/bg-gray-200\/10 p-4 rounded-lg border border-black/g, 'bg-gray-100 p-4 border-4 border-black shadow-[4px_4px_0px_#000] transform skew-x-1');
c = c.replace(/border border-\[\#451a03\]/g, 'border-4 border-black transform skew-x-2');
fs.writeFileSync('src/components/documents/TearSheet.jsx', c);

let a = fs.readFileSync('src/components/dashboard/SessionArchive.jsx', 'utf-8');
a = a.replace(/text-\[\#d97706\]/g, 'text-[#FF0055]');
a = a.replace(/bg-\[\#fcd34d\]\/20/g, 'bg-[#00E5FF]');
a = a.replace(/shadow-\[0_0_10px_\#d97706\]/g, 'shadow-[2px_2px_0px_#000]');
a = a.replace(/text-\[\#166534\]/g, 'text-[#00E676]');
a = a.replace(/text-\[\#991b1b\]/g, 'text-[#FF0055]');
a = a.replace(/color: '\#ef4444'/g, "color: '#FF0055'");
a = a.replace(/color: '\#64748b'/g, "color: '#A855F7'");
a = a.replace(/color: '\#3b82f6'/g, "color: '#00E5FF'");
a = a.replace(/stroke=\"\#451a03\"/g, 'stroke="#000000"');
a = a.replace(/backgroundColor: '\#292524'/g, "backgroundColor: '#FFFFFF'");
a = a.replace(/border: '1px solid \#d97706'/g, "border: '4px solid #000'");
a = a.replace(/color: '\#fcd34d'/g, "color: '#000000'");
a = a.replace(/text-\[\#ea580c\]/g, 'text-[#FF0055]');
a = a.replace(/fill: '\#d4d4d8'/g, "fill: '#000000'");
a = a.replace(/fill=\"\#ea580c\"/g, 'fill="#FF0055"');
a = a.replace(/Pressure Gauges/g, 'Session Analytics');
fs.writeFileSync('src/components/dashboard/SessionArchive.jsx', a);
